easy_admin:
    site_name: '<span style="font-weight:300">Symph</span>Admin'
    entities:
        Product:
            class: App\Entity\Product
            list:
                fields:
                  - 'id'
                  - 'name'
                  - 'description'
                  - 'img'
                  - 'discount'
                  - 'quantity'
                  - { property: 'img', type: 'image', base_path: 'images/products'}
            form:
                fields:
                  - 'name'
                  - 'description'
                  - 'price'
                  - 'discount'
                  - 'quantity'
                  - { property: 'imageFile', type: 'vich_image' }

        Discount:
            class: App\Entity\Discount

        Order:
            class: App\Entity\Order

    design:
        brand_color: '#34495e'