#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\ProductsController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

register:
    path: /register
    controller: App\Controller\RegistrationController::register

product_show:
    path: /product/{name}
    controller: App\Controller\ProductsController::show

cart_add:
    path: /cart/add/{id}
    controller: App\Controller\ProductsController::addToShoppingCart

cart_show:
    path: /cart
    controller: App\Controller\ProductsController::showShoppingCart